### ISSUE TITLE
移动热修复初始化无限 AndroidRuntime 异常

### ISSUE THREAD

**Issue by 13120241790** [alibaba/dpa-demo-android#257]
1. 产品： 移动热修复
2. sdk版本：3.3.8

3. 设备信息：10 rk3568
4. 问题描述：
初始化无限 AndroidRuntime
2023-06-29 19:30:20.749 31171-31171/? E/AndroidRuntime:     at com.thunder.ktvlite.LiteApplication.onCreate(LiteApplication.kt:49)
        at com.taobao.sophix.a.c.b(Sophix:687)
        at com.taobao.sophix.a.e.a(Sophix:296)
        at com.taobao.sophix.SophixApplication.onCreate(Sophix:16)
        at com.thunder.ktvlite.LiteApplication.onCreate(LiteApplication.kt:49)
        at com.taobao.sophix.a.c.b(Sophix:687)
        at com.taobao.sophix.a.e.a(Sophix:296)
6. 复现步骤：
启动必现

**Comment by fancychendong** [comment]
你好，请问最后有修复吗？
